-- ==============================================================================
-- GYMBro Canonical Database Schema (schema.sql)
-- Consolidated, fully-indexed PostgreSQL / Supabase schema for GYMBro
-- ==============================================================================

-- 1. Enable Required Extensions
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ------------------------------------------------------------------------------
-- 2. Users & Athlete Profiles
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL, -- Hashed password
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Profile & Physiology
  age INT,
  weight NUMERIC,
  height NUMERIC,
  sport_history TEXT,
  running_experience TEXT,
  past_injuries TEXT,
  lifestyle TEXT,
  weekly_availability TEXT,
  terrain_preference TEXT,
  equipment TEXT,
  
  -- Dynamic Multi-Goal Composite
  goals JSONB DEFAULT '{}'::jsonb,
  
  -- Third-Party Integration Credentials & Tokens
  garmin_email TEXT,
  garmin_password TEXT, -- Encrypted
  strava_access_token TEXT,
  strava_refresh_token TEXT,
  strava_last_updated TIMESTAMP WITH TIME ZONE,
  
  -- Agent & Training State
  coach_status TEXT DEFAULT 'initial',
  coach_name TEXT DEFAULT 'AI Coach',
  interview_chat_id BIGINT,
  training_plan JSONB,
  training_plan_generated_at TIMESTAMP WITH TIME ZONE,
  training_plan_phased JSONB,
  training_plan_phased_at TIMESTAMP WITH TIME ZONE,
  
  -- Onboarding/Interview state
  interview_started_at TIMESTAMP WITH TIME ZONE,
  interview_completed_at TIMESTAMP WITH TIME ZONE,
  interview_step INT DEFAULT 1,
  
  -- Garmin Sync State
  garmin_sync_status VARCHAR(50) DEFAULT 'not_connected',
  garmin_sync_progress INTEGER DEFAULT 0,
  garmin_last_sync_error TEXT,
  garmin_sync_started_at TIMESTAMP WITH TIME ZONE,
  garmin_sync_completed_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);

-- ------------------------------------------------------------------------------
-- 3. Chats & Agent Interactions
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT,
  messages JSONB DEFAULT '[]'::jsonb, -- Array of message objects with ui_payload
  type TEXT DEFAULT 'general',        -- 'general', 'interview', 'planning'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_chats_user_id ON public.chats(user_id);

-- ------------------------------------------------------------------------------
-- 4. Unified Daily Biometrics (Single Source of Truth for Daily Wellness)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.biometrics_daily (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  
  -- Heart Rate & Autonomic Nervous System
  resting_hr INT,
  hrv NUMERIC,              -- Nightly avg rMSSD/SDNN in ms
  hrv_ms INT,               -- Legacy alias for compatibility
  hrv_status TEXT,          -- 'Balanced', 'Low', 'Unbalanced'
  
  -- Sleep Architecture
  sleep_score INT,          -- 0-100
  sleep_hours NUMERIC(4,2), -- Total hours
  deep_sleep_hours NUMERIC(4,2),
  rem_sleep_hours NUMERIC(4,2),
  light_sleep_hours NUMERIC(4,2),
  sleep_stages JSONB,       -- {"deep": sec, "rem": sec, "light": sec, "awake": sec}
  
  -- Readiness & Energy
  recovery_score INT,       -- 0-100
  body_battery INT,         -- 0-100
  stress_level NUMERIC,     -- 0-100
  
  -- Performance & Cardiovascular Baselines
  vo2_max NUMERIC(5,2),     -- ml/kg/min
  fitness_age NUMERIC(4,1),
  training_status TEXT,     -- 'PRODUCTIVE', 'MAINTAINING', 'RECOVERY', 'OVERREACHING'
  acute_load NUMERIC,
  
  -- Respiration & Oxygen
  spo2 NUMERIC(5,2),        -- %
  respiration NUMERIC(4,1), -- Breaths per min
  
  -- Daily Movement Totals
  steps INT,
  calories_burned INT,
  
  -- Source & Provenance
  source TEXT DEFAULT 'garmin', -- 'garmin' | 'apple_health' | 'manual'
  raw_source VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

CREATE INDEX IF NOT EXISTS idx_biometrics_daily_user_date ON public.biometrics_daily(user_id, date DESC);

-- ------------------------------------------------------------------------------
-- 5. Activities & Workout Streams
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.garmin_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  activity_id TEXT UNIQUE NOT NULL,
  activity_name TEXT,
  start_time_local TIMESTAMP,
  distance NUMERIC,         -- Meters
  duration NUMERIC,         -- Seconds
  calories NUMERIC,
  activity_type TEXT,
  raw_data JSONB,
  details JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  -- Detailed Performance Metrics
  average_hr NUMERIC,
  max_hr NUMERIC,
  elevation_gain NUMERIC,
  average_speed NUMERIC,    -- m/s
  max_speed NUMERIC,        -- m/s
  average_cadence NUMERIC
);

CREATE INDEX IF NOT EXISTS idx_garmin_activities_user ON public.garmin_activities(user_id, start_time_local DESC);

CREATE TABLE IF NOT EXISTS public.strava_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  activity_id TEXT UNIQUE NOT NULL,
  name TEXT,
  type TEXT,
  distance NUMERIC,         -- Meters
  moving_time NUMERIC,      -- Seconds
  elapsed_time NUMERIC,     -- Seconds
  total_elevation_gain NUMERIC,
  start_date_local TIMESTAMP,
  average_speed NUMERIC,
  max_speed NUMERIC,
  calories NUMERIC,
  raw_data JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  -- Performance Metrics
  average_hr NUMERIC,
  max_hr NUMERIC,
  elevation_gain NUMERIC,
  average_speed_perf NUMERIC,
  max_speed_perf NUMERIC,
  average_cadence NUMERIC
);

CREATE INDEX IF NOT EXISTS idx_strava_activities_user ON public.strava_activities(user_id, start_date_local DESC);

CREATE TABLE IF NOT EXISTS public.activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  activity_type TEXT NOT NULL,
  name TEXT,
  start_time_local TIMESTAMP,
  distance NUMERIC,
  duration NUMERIC,
  calories NUMERIC,
  average_hr NUMERIC,
  max_hr NUMERIC,
  elevation_gain NUMERIC,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_activities_user ON public.activities(user_id, start_time_local DESC);

-- Garmin Specific Raw Sub-tables (optional caching)
CREATE TABLE IF NOT EXISTS public.garmin_daily (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  steps JSONB,
  heartrate JSONB,
  stress JSONB,
  respiration JSONB,
  spo2 JSONB,
  resting_hr JSONB,
  floors JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

CREATE TABLE IF NOT EXISTS public.garmin_sleep (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  sleep_data JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

CREATE TABLE IF NOT EXISTS public.garmin_maxmetrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  max_metrics JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

-- ------------------------------------------------------------------------------
-- 6. User Baselines & Longitudinal Analytics
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_baselines (
  id SERIAL PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  metric_category VARCHAR(50) NOT NULL, -- 'running', 'health', 'training_load', 'prs'
  baselines JSONB NOT NULL,
  computed_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, metric_category)
);

CREATE INDEX IF NOT EXISTS idx_user_baselines_user_id ON public.user_baselines(user_id);

-- ------------------------------------------------------------------------------
-- 7. Training Events & Interactive Calendar
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.training_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  event_type TEXT CHECK (event_type IN ('run', 'strength', 'rest', 'race', 'cross_train', 'other')) NOT NULL,
  status TEXT CHECK (status IN ('planned', 'completed', 'skipped')) DEFAULT 'planned',
  created_by TEXT CHECK (created_by IN ('user', 'coach', 'agent')) DEFAULT 'user',
  metrics JSONB DEFAULT '{}'::jsonb, -- structured targets (target_pace, sets/reps, zone)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_training_events_user_date ON public.training_events(user_id, date);

-- ------------------------------------------------------------------------------
-- 8. Clinical Lab Biomarkers & Panels
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lab_panels (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  test_date DATE NOT NULL,
  provider_name VARCHAR(100),
  pdf_storage_path TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lab_panels_user ON public.lab_panels(user_id, test_date DESC);

CREATE TABLE IF NOT EXISTS public.biomarkers (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  panel_id UUID REFERENCES public.lab_panels(id) ON DELETE CASCADE,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  marker_name VARCHAR(100) NOT NULL,
  value NUMERIC(10,2) NOT NULL,
  unit VARCHAR(30),
  ref_range_min NUMERIC(10,2),
  ref_range_max NUMERIC(10,2),
  status VARCHAR(30) DEFAULT 'optimal', -- 'optimal', 'flagged_low', 'flagged_high'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_biomarkers_user_marker ON public.biomarkers(user_id, marker_name);

-- ------------------------------------------------------------------------------
-- 9. Nutrition & Meal Photo Logs
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.meals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  logged_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  meal_type VARCHAR(30), -- 'breakfast', 'lunch', 'dinner', 'snack'
  item_name TEXT,
  image_url TEXT,
  calories INT,
  protein_g NUMERIC(5,1),
  carbs_g NUMERIC(5,1),
  fat_g NUMERIC(5,1),
  quality_score INT,
  coach_notes TEXT
);

CREATE INDEX IF NOT EXISTS idx_meals_user_date ON public.meals(user_id, logged_at DESC);

-- ------------------------------------------------------------------------------
-- 10. Daily Recovery Journals
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.daily_journals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  answers JSONB DEFAULT '{}'::jsonb, -- {"energy_level": 8, "felt_sore": false, "journal_text": "..."}
  energy_level INT,
  felt_sore BOOLEAN DEFAULT FALSE,
  journal_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, date)
);

CREATE INDEX IF NOT EXISTS idx_daily_journals_user_date ON public.daily_journals(user_id, date DESC);

-- ------------------------------------------------------------------------------
-- 11. Unified Long-Term Memory & User Intelligence (Vector RAG)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.user_intelligence (
  id SERIAL PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  category VARCHAR(50) NOT NULL, 
  -- 'fact', 'preference', 'goal', 'injury', 'nutrition', 'training_philosophy', 'interaction'
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  embedding vector(768), -- Gemini standard 768-dimension embedding
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_intelligence_user_id ON public.user_intelligence(user_id);
CREATE INDEX IF NOT EXISTS idx_intelligence_category ON public.user_intelligence(category);
CREATE INDEX IF NOT EXISTS idx_intelligence_embedding_hnsw ON public.user_intelligence USING hnsw (embedding vector_cosine_ops);

-- Search function for semantic intelligence matching
CREATE OR REPLACE FUNCTION match_intelligence (
  query_embedding vector(768),
  match_user_id int,
  match_count int DEFAULT 5,
  match_threshold float DEFAULT 0.5,
  filter_categories varchar[] DEFAULT NULL
)
RETURNS TABLE (
  id int,
  content text,
  category varchar,
  similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ui.id,
    ui.content,
    ui.category,
    (1 - (ui.embedding <=> query_embedding))::float AS similarity
  FROM user_intelligence ui
  WHERE ui.user_id = match_user_id
  AND (filter_categories IS NULL OR ui.category = ANY(filter_categories))
  AND (1 - (ui.embedding <=> query_embedding)) > match_threshold
  ORDER BY ui.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- Trigger for user_intelligence updated_at
CREATE OR REPLACE FUNCTION update_intelligence_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_intelligence_updated_at
  BEFORE UPDATE ON public.user_intelligence
  FOR EACH ROW
  EXECUTE FUNCTION update_intelligence_updated_at();

-- ------------------------------------------------------------------------------
-- 12. Knowledge Graph Entity Relational Store (Graph RAG)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.health_graph (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  source_node VARCHAR(100) NOT NULL,
  target_node VARCHAR(100) NOT NULL,
  relationship_type VARCHAR(50) NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_health_graph_user ON public.health_graph(user_id);
