-- Enable pgvector extension for future RAG usage
create extension if not exists vector;
-- Users Table (Custom Auth for now, mirroring MongoDB structure)
create table public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null, -- Hashed password
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Profile Fields
  age int,
  weight numeric,
  height numeric,
  sport_history text,
  running_experience text,
  past_injuries text,
  lifestyle text,
  weekly_availability text,
  terrain_preference text,
  equipment text,
  
  -- JSONB fields for flexibility
  goals jsonb default '{}'::jsonb,
  
  -- Integrations
  garmin_email text,
  garmin_password text, -- Encrypted
  strava_access_token text,
  strava_refresh_token text,
  strava_last_updated timestamp with time zone,
  
  -- Coach State
  coach_status text default 'initial', -- 'initial', 'interview_in_progress', 'plan_generated', 'plan_phased'
  interview_chat_id bigint,
  training_plan jsonb,
  training_plan_generated_at timestamp with time zone,
  training_plan_phased jsonb,
  training_plan_phased_at timestamp with time zone
);
-- Chats Table
create table public.chats (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  title text,
  messages jsonb default '[]'::jsonb, -- Array of message objects
  type text default 'general', -- 'general', 'interview'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Garmin Activities Table
create table public.garmin_activities (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  activity_id text unique not null,
  activity_name text,
  start_time_local timestamp,
  distance numeric,
  duration numeric,
  calories numeric,
  activity_type text,
  raw_data jsonb,
  synced_at timestamp with time zone default timezone('utc'::text, now())
);
-- Garmin Daily Metrics Table
create table public.garmin_daily (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  date date not null,
  steps jsonb,
  heartrate jsonb,
  stress jsonb,
  respiration jsonb,
  spo2 jsonb,
  resting_hr jsonb,
  floors jsonb,
  synced_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, date)
);
-- Garmin Sleep Table
create table public.garmin_sleep (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  date date not null,
  sleep_data jsonb,
  synced_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, date)
);
-- Garmin Max Metrics (VO2 Max, etc.)
create table public.garmin_maxmetrics (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  date date not null,
  max_metrics jsonb,
  synced_at timestamp with time zone default timezone('utc'::text, now()),
  unique(user_id, date)
);
-- Strava Activities Table
create table public.strava_activities (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade not null,
  activity_id text unique not null,
  name text,
  type text,
  distance numeric,
  moving_time numeric,
  elapsed_time numeric,
  total_elevation_gain numeric,
  start_date_local timestamp,
  average_speed numeric,
  max_speed numeric,
  calories numeric,
  raw_data jsonb,
  synced_at timestamp with time zone default timezone('utc'::text, now())
);

ALTER TABLE garmin_activities ADD COLUMN IF NOT EXISTS details JSONB;

CREATE TABLE IF NOT EXISTS user_baselines (
    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    metric_category VARCHAR(50) NOT NULL,  -- 'running', 'health', 'training_load'
    baselines JSONB NOT NULL,              -- Computed baseline values
    computed_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, metric_category)
);

-- Index for fast lookups
CREATE INDEX IF NOT EXISTS idx_user_baselines_user_id ON user_baselines(user_id);
