-- Training Events Table
CREATE TABLE IF NOT EXISTS public.training_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_type TEXT CHECK (event_type IN ('run', 'strength', 'rest', 'race', 'other')),
    status TEXT CHECK (status IN ('planned', 'completed', 'skipped')) DEFAULT 'planned',
    created_by TEXT CHECK (created_by IN ('user', 'coach')) DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast retrieval by date range
CREATE INDEX IF NOT EXISTS idx_training_events_user_date ON training_events(user_id, date);
