-- Consolidated schema.sql for fresh Supabase Database initialization

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Users Table
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  PASSWORD TEXT NOT NULL, -- Hashed password
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  
  -- Profile Fields
  age INT,
  weight NUMERIC,
  height NUMERIC,
  sport_history TEXT,
  running_experience TEXT,
  past_injuries TEXT,
  lifestyle TEXT,
  weekly_availability TEXT,
  terrain_preference TEXT,
  equipment TEXT,
  
  -- JSONB fields for flexibility
  goals JSONB DEFAULT '{}'::jsonb,
  
  -- Integrations
  garmin_email TEXT,
  garmin_password TEXT, -- Encrypted
  strava_access_token TEXT,
  strava_refresh_token TEXT,
  strava_last_updated TIMESTAMP WITH TIME ZONE,
  
  -- Coach State
  coach_status TEXT DEFAULT 'initial',
  interview_chat_id BIGINT,
  training_plan JSONB,
  training_plan_generated_at TIMESTAMP WITH TIME ZONE,
  training_plan_phased JSONB,
  training_plan_phased_at TIMESTAMP WITH TIME ZONE,
  
  -- Onboarding/Interview state
  interview_started_at TIMESTAMP WITH TIME ZONE,
  interview_completed_at TIMESTAMP WITH TIME ZONE,
  interview_step INT DEFAULT 1,
  
  -- Garmin Sync State
  garmin_sync_status VARCHAR(50) DEFAULT 'not_connected',
  garmin_sync_progress INTEGER DEFAULT 0,
  garmin_last_sync_error TEXT,
  garmin_sync_started_at TIMESTAMP WITH TIME ZONE,
  garmin_sync_completed_at TIMESTAMP WITH TIME ZONE
);

-- 3. Chats Table
CREATE TABLE IF NOT EXISTS public.chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  title TEXT,
  messages JSONB DEFAULT '[]'::jsonb, -- Array of message objects
  type TEXT DEFAULT 'general', -- 'general', 'interview'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Garmin Activities Table
CREATE TABLE IF NOT EXISTS public.garmin_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  activity_id TEXT UNIQUE NOT NULL,
  activity_name TEXT,
  start_time_local TIMESTAMP,
  distance NUMERIC,
  duration NUMERIC,
  calories NUMERIC,
  activity_type TEXT,
  raw_data JSONB,
  details JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  -- Performance fields
  average_hr NUMERIC,
  max_hr NUMERIC,
  elevation_gain NUMERIC,
  average_speed NUMERIC,
  max_speed NUMERIC,
  average_cadence NUMERIC
);

-- 5. Garmin Daily Metrics Table
CREATE TABLE IF NOT EXISTS public.garmin_daily (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  steps JSONB,
  heartrate JSONB,
  stress JSONB,
  respiration JSONB,
  spo2 JSONB,
  resting_hr JSONB,
  floors JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

-- 6. Garmin Sleep Table
CREATE TABLE IF NOT EXISTS public.garmin_sleep (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  sleep_data JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

-- 7. Garmin Max Metrics Table (VO2 Max, etc.)
CREATE TABLE IF NOT EXISTS public.garmin_maxmetrics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  max_metrics JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, date)
);

-- 8. Strava Activities Table
CREATE TABLE IF NOT EXISTS public.strava_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  activity_id TEXT UNIQUE NOT NULL,
  name TEXT,
  type TEXT,
  distance NUMERIC,
  moving_time NUMERIC,
  elapsed_time NUMERIC,
  total_elevation_gain NUMERIC,
  start_date_local TIMESTAMP,
  average_speed NUMERIC,
  max_speed NUMERIC,
  calories NUMERIC,
  raw_data JSONB,
  synced_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  
  -- Performance fields
  average_hr NUMERIC,
  max_hr NUMERIC,
  elevation_gain NUMERIC,
  average_speed_perf NUMERIC,
  max_speed_perf NUMERIC,
  average_cadence NUMERIC
);

-- 9. User Baselines Table
CREATE TABLE IF NOT EXISTS public.user_baselines (
    id SERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    metric_category VARCHAR(50) NOT NULL,  -- 'running', 'health', 'training_load'
    baselines JSONB NOT NULL,              -- Computed baseline values
    computed_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, metric_category)
);
CREATE INDEX IF NOT EXISTS idx_user_baselines_user_id ON user_baselines(user_id);

-- 10. Training Events Table (Calendar)
CREATE TABLE IF NOT EXISTS public.training_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    event_type TEXT CHECK (event_type IN ('run', 'strength', 'rest', 'race', 'other')),
    status TEXT CHECK (status IN ('planned', 'completed', 'skipped')) DEFAULT 'planned',
    created_by TEXT CHECK (created_by IN ('user', 'coach')) DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_training_events_user_date ON training_events(user_id, date);

-- 11. User Intelligence Table (Unified memory & RAG facts)
CREATE TABLE IF NOT EXISTS public.user_intelligence (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category VARCHAR(50) NOT NULL, 
    -- 'fact', 'preference', 'goal', 'injury', 'nutrition', 'training_philosophy', 'interaction'
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}',
    embedding vector(768), -- Gemini standard dimension
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_intelligence_user_id ON user_intelligence(user_id);
CREATE INDEX IF NOT EXISTS idx_intelligence_category ON user_intelligence(category);
CREATE INDEX IF NOT EXISTS idx_intelligence_embedding_hnsw ON user_intelligence USING hnsw (embedding vector_cosine_ops);

-- 12. Search function for the new intelligence layer
CREATE OR REPLACE FUNCTION match_intelligence (
    query_embedding vector(768),
    match_user_id int,
    match_count int DEFAULT 5,
    match_threshold float DEFAULT 0.5,
    filter_categories varchar[] DEFAULT NULL
)
RETURNS TABLE (
    id int,
    content text,
    category varchar,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        ui.id,
        ui.content,
        ui.category,
        1 - (ui.embedding <=> query_embedding) AS similarity
    FROM user_intelligence ui
    WHERE ui.user_id = match_user_id
    AND (filter_categories IS NULL OR ui.category = ANY(filter_categories))
    AND 1 - (ui.embedding <=> query_embedding) > match_threshold
    ORDER BY ui.embedding <=> query_embedding
    LIMIT match_count;
END;
$$;

-- 13. Trigger for updated_at
CREATE OR REPLACE FUNCTION update_intelligence_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER trigger_intelligence_updated_at
    BEFORE UPDATE ON user_intelligence
    FOR EACH ROW
    EXECUTE FUNCTION update_intelligence_updated_at();
